spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_CI_URL}
    username: ${MYSQL_USER}
  jpa: 
    hibernate: 
      ddl-auto: create-drop
    show-sql: true
server:
  port: 9041
